### ISSUE TITLE
Delete 기능 구현 중 문제 (article 객체의 id / 로그인 기능 필요) 

### ISSUE THREAD

**Issue by dy6578ekdbs** [dy6578ekdbs/EFUB_Toy_Project_Twitter#12]
### Delete api 구현 중 문제 발생

1. 로그인 기능 필요
- api 명세서에 따르면 삭제 요청 시 userId를 확인하는 절차가 포함되어있음. 하지만 현재 프론트에는 userId를 바꾸는 기능이 없음. 간단하게라도 로그인하는 기능이 필요할 것 같음 

![image](https://user-images.githubusercontent.com/81161750/167841028-9c32ea9e-842f-4780-8805-93c0303e4d25.png)

2. 삭제 요청 시 api안에 tweet_id를 넣어 보내야하는데, Article.js 컴포넌트는 articles 배열의 **객체 1개만** 받아오기 때문에 해당 객체의 index를 알 수 없음.  (물론.. 방법이 있을지도... 내가 무지했을지도....)

-> 백엔드 분들에게 객체 정보 안에 index도 추가해줄 수 있냐고 부탁드리는 것은 어떨까요 ? 

![image](https://user-images.githubusercontent.com/81161750/167840795-d2944480-9013-4fde-b76e-779125f0f45e.png)

**Comment by SJ-Lee33** [comment]
1. 로그인 기능 필요

저희가 어차피 유저가 하나니까.. 별도의 로그인 과정 없이 삭제할 때 userId가 1인지 아닌지만 체크하는 걸로 축소하면 어떨까요?

**Comment by SJ-Lee33** [comment]
2. 삭제 요청 시 tweet_id

저도 api/tweets 에 대한 응답으로 tweet_id 받도록 하는게 맞는거같아요!! 백엔드 분들께 요청 드려 봅시다!
